[facility]
name = "Advanced Photon Source"

[beamline]
name = "25-ID-D"
is_connected = true

[database.databroker]

catalog = "s25idd"

[queueserver]
kafka_topic = "s25idd_queueserver"
control_host = "fedorov"
control_port = "60616"
info_host = "fedorov"
info_port = "60626"

[shutter]

[shutter.A]

open_pv = "PSS:25ID:FES_OPEN_EPICS.VAL"
close_pv = "PSS:25ID:FES_CLOSE_EPICS.VAL"
status_pv = "PSS:25ID:A_BEAM_PRESENT"

[shutter.D]

open_pv = "PSS:25ID:SDS_OPEN_EPICS.VAL"
close_pv = "PSS:25ID:SDS_CLOSE_EPICS.VAL"
status_pv = "PSS:25ID:D_BEAM_PRESENT"

[ion_chamber.scaler]
ioc = "25iddVME"
record = "3820:scaler1"
channels = [2, 3, 4, 5, 6, 7, 8]

[ion_chamber.preamp]
ioc = "25idd"

[motor.VME_crate]
prefix = "25iddVME"
num_motors = 56

[motor.IRM]
prefix = "25ida:IRM"
num_motors = 5

[motor.WB_slit]
prefix = "25ida:slits"
num_motors = 8

[stage.Aerotech]
prefix = "25idd"
pv_vert = ":m2"
pv_horiz = ":m1"

[monochromator]
ioc = "25idbLerix"
ioc_branch = "Lerix"

[undulator]
ioc = "ID25us"

[camera]
imagej_command = "/home/beams/S25IDCUSER/ImageJ/ImageJ"

[camera.camBPM]
name = "Hutch A BPM"
description = "Hutch A BPM"
ioc = "25idaBPM"

[camera.camA]
name = "s25id-gige-A"
description = "GigE Vision A"
ioc = "25idgigeA"

[camera.camB]
name = "s25id-gige-B"
description = "GigE Vision B"
ioc = "25idgigeB"

[camera.camC]
name = "s25id-gige-C"
description = "GigE Vision C"
ioc = "25idgigeC"

[camera.camD]
name = "s25id-gige-D"
description = "GigE Vision D"
ioc = "25idgigeD"

[camera.camE]
name = "s25id-gige-E"
description = "GigE Vision E"
ioc = "25idgigeE"
